name: company_insight_app
description: "The 'Company Insight App' allows users to search for companies by symbol (e.g., AAPL,
MSFT), view a list of companies they're interested in, and delve into detailes of each
company. This app aims to provide valuable information to users, including financial data and
market presence, enabling them to make informed decisions or simply satisfy their curiosity
about a company's standing and operations"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^12.1.1
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  injectable: ^2.3.2
  freezed: ^2.4.5
  get_it: ^7.6.4
  bloc_test: ^9.1.5
  mockito: ^5.4.3
  gap: ^3.0.1
  flutter_localizations:
    sdk: flutter
  intl: any
  equatable: any
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.1
  floor: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  floor_generator: ^1.4.2

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/

flutter_intl:
  enabled: true
  class_name: L10n
  arb_dir: assets/l10n
  output_dir: lib/translations