name: company_insight_app
description: "The 'Company Insight App' allows users to search for companies by symbol (e.g., AAPL,
MSFT), view a list of companies they're interested in, and delve into detailes of each
company. This app aims to provide valuable information to users, including financial data and
market presence, enabling them to make informed decisions or simply satisfy their curiosity
about a company's standing and operations"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  go_router: ^13.2.2
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  injectable: ^2.3.2
  freezed: ^2.4.5
  get_it: ^7.6.4
  bloc_test: ^9.1.5
  bloc: ^8.1.2
  mockito: ^5.4.3
  bloc_concurrency: ^0.2.5
  gap: ^3.0.1
  flutter_localizations:
    sdk: flutter
  intl: any
  equatable: any
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.0
  floor: ^1.4.2
  flutter_svg: ^2.0.10+1
  flutter_keyboard_visibility: ^6.0.0
  flutter_animate: ^4.4.0
  pretty_dio_logger: ^1.3.1
  shimmer: ^3.0.0
  rxdart: ^0.27.7
  another_flushbar: ^1.12.30

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  floor_generator: ^1.4.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  rename_app: ^1.3.2

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Novatica
      fonts:
        - asset: assets/fonts/novatica/Novatica-Bold.ttf
          weight: 700
        - asset: assets/fonts/novatica/Novatica-Medium.ttf
          weight: 500
        - asset: assets/fonts/novatica/Novatica.ttf
          weight: 400
        - asset: assets/fonts/novatica/NovaticaLight.ttf
          weight: 300
    - family: EuclidCircularB
      fonts:
        - asset: assets/fonts/euclidCircularB/EuclidCircularB-Bold.ttf
          weight: 700
        - asset: assets/fonts/euclidCircularB/EuclidCircularB-Medium.ttf
          weight: 500
        - asset: assets/fonts/euclidCircularB/EuclidCircularB-Regular.ttf
          weight: 400
        - asset: assets/fonts/euclidCircularB/EuclidCircularB-Light.ttf
          weight: 300

flutter_intl:
  enabled: true
  class_name: L10n
  arb_dir: assets/l10n
  output_dir: lib/translations

flutter_native_splash:
  color: "#020403"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21